#!/usr/bin/env python3
"""Generate a tap formula from verified release archives, without publishing it."""
import hashlib
from pathlib import Path
import re
import sys


def formula(version, directory):
    if not re.fullmatch(r"v?\d+\.\d+\.\d+", version):
        raise ValueError("expected a stable vX.Y.Z version")
    version = version.removeprefix("v")
    lines = [
        "# Generated by scripts/homebrew-formula.py from release archives.",
        "class Co < Formula",
        '  desc "Human command-line client for co.codes"',
        '  homepage "https://co.codes"',
        f'  version "{version}"',
        '  license any_of: ["MIT", "Apache-2.0"]',
        '  depends_on "git"',
    ]
    for os, target_os in [("macos", "apple-darwin"), ("linux", "unknown-linux-musl")]:
        lines += ["", f"  on_{os} do"]
        for arch, target_arch in [("arm", "aarch64"), ("intel", "x86_64")]:
            asset = f"co-{target_arch}-{target_os}.tar.gz"
            checksum = hashlib.sha256((directory / asset).read_bytes()).hexdigest()
            expected = (directory / (asset + ".sha256")).read_text().split()
            if expected != [checksum, asset]:
                raise ValueError(f"checksum mismatch for {asset}")
            lines += [f"    on_{arch} do", f'      url "https://github.com/codotcodes/co/releases/download/v{version}/{asset}"', f'      sha256 "{checksum}"', "    end"]
        lines += ["  end"]
    lines += ["", "  def install", '    bin.install "co"', "  end", "", "  test do", '    assert_equal "co #{version}", shell_output("#{bin}/co version").strip', "  end", "end", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: homebrew-formula.py VERSION RELEASE_DIRECTORY")
    print(formula(sys.argv[1], Path(sys.argv[2])), end="")
